FROM fedora:32

LABEL org.opencontainers.image.base.name="fedora:32"
LABEL org.opencontainers.image.authors="Christian Heimes"
LABEL org.opencontainers.image.url="https://github.com/tiran/cpython_builddep/"
LABEL org.opencontainers.image.title="CPython build dependencies for fedora:32"
LABEL org.opencontainers.image.description="Container with CPython build dependencies"
LABEL org.opencontainers.image.usage="podman run --rm -ti -v .:/cpython:Z quay.io/tiran/cpythonbuild:fedora-32"

ENV PYBUILDDEP_FROMDISTRO="fedora:32"
ENV PYBUILDDEP_DISTROTAG="fedora-32"
VOLUME ["/cpython"]

COPY tests/entry.sh /
CMD ["/entry.sh"]

COPY builddep.sh /
RUN ["/builddep.sh", "--update", "--extras", "--cleanup"]
