FROM ubuntu:bionic

LABEL org.opencontainers.image.base.name="ubuntu:bionic"
LABEL org.opencontainers.image.authors="Christian Heimes"
LABEL org.opencontainers.image.url="https://github.com/tiran/cpython_builddep/"
LABEL org.opencontainers.image.title="CPython build dependencies for ubuntu:bionic"
LABEL org.opencontainers.image.description="Container with CPython build dependencies"
LABEL org.opencontainers.image.usage="podman run --rm -ti -v .:/cpython:Z quay.io/tiran/cpythonbuild:ubuntu-bionic"

ENV PYBUILDDEP_DISTRO="ubuntu:bionic"
VOLUME ["/cpython"]

COPY tests/entry.sh /
CMD ["/entry.sh"]

COPY builddep.sh /
RUN ["/builddep.sh", "--update", "--extras", "--cleanup"]
