FROM fedora:35

LABEL org.opencontainers.image.base.name="fedora:35"
LABEL org.opencontainers.image.authors="Christian Heimes"
LABEL org.opencontainers.image.url="https://github.com/tiran/cpython_builddep/"
LABEL org.opencontainers.image.title="CPython build dependencies for fedora:35"
LABEL org.opencontainers.image.description="Container with CPython build dependencies"
LABEL org.opencontainers.image.usage="podman run --rm -ti -v .:/cpython:Z quay.io/tiran/cpythonbuild:fedora-35"

ENV PYBUILDDEP_FROMDISTRO="fedora:35"
ENV PYBUILDDEP_DISTROTAG="fedora-35"
ENV PYBUILDDEP_SRCDIR=/cpython
VOLUME ["/cpython"]
WORKDIR /cpython

COPY tests/entry.sh tests/cmd.sh /
ENTRYPOINT ["/entry.sh"]
CMD ["/cmd.sh"]

COPY builddep.sh /
RUN ["/builddep.sh", "--update", "--extras", "--cleanup"]
