FROM alpine:3.12

LABEL org.opencontainers.image.base.name="alpine:3.12"
LABEL org.opencontainers.image.authors="Christian Heimes"
LABEL org.opencontainers.image.url="https://github.com/tiran/cpython_builddep/"
LABEL org.opencontainers.image.title="CPython build dependencies for alpine:3.12"
LABEL org.opencontainers.image.description="Container with CPython build dependencies"
LABEL org.opencontainers.image.usage="podman run --rm -ti -v .:/cpython:Z quay.io/tiran/cpythonbuild:alpine-3.12"

ENV PYBUILDDEP_FROMDISTRO="alpine:3.12"
ENV PYBUILDDEP_DISTROTAG="alpine-3.12"
ENV PYBUILDDEP_SRCDIR=/cpython
VOLUME ["/cpython"]

COPY tests/entry.sh tests/cmd.sh /
ENTRYPOINT ["/entry.sh"]
CMD ["/cmd.sh"]

COPY builddep.sh /
RUN ["/builddep.sh", "--update", "--extras", "--cleanup"]
